#!/usr/bin/env python3
"""Generate a GitHub PR comment body from sandbox metrics JSON files.

Usage:
    python scripts/ci/metrics_comment.py sandbox_metrics_daytona.json [sandbox_metrics_docker.json ...]

Reads one or more JSON reports produced by --sandbox-metrics and prints
a Markdown comment to stdout.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _fmt(val: float, unit: str = "s") -> str:
    if val < 0.01:
        return f"{val * 1000:.0f}ms"
    return f"{val:.2f}{unit}"


def _provider_table(provider: str, summary: dict) -> list[str]:
    lines: list[str] = []
    by_cat = summary.get("by_category", {})
    if not by_cat:
        return lines

    total_ops = summary.get("total_operations", 0)
    total_dur = summary.get("total_duration_s", 0)
    success_rate = summary.get("success_rate", 0)

    lines.append(f"### {provider.capitalize()}")
    lines.append("")
    lines.append("| Category | Ops | Mean | Median | P95 | Max |")
    lines.append("|----------|----:|-----:|-------:|----:|----:|")

    for cat, stats in sorted(by_cat.items()):
        lines.append(
            f"| {cat} | {stats['count']} "
            f"| {_fmt(stats['mean_s'])} "
            f"| {_fmt(stats['median_s'])} "
            f"| {_fmt(stats['p95_s'])} "
            f"| {_fmt(stats['max_s'])} |"
        )

    lines.append("")
    lines.append(
        f"**Total:** {total_ops} ops, {_fmt(total_dur)}, "
        f"{success_rate * 100:.0f}% success"
    )
    lines.append("")
    return lines


def _comparison_table(comparison: dict) -> list[str]:
    if not comparison:
        return []

    lines: list[str] = []
    lines.append("### Cross-Provider Comparison")
    lines.append("")

    # Collect all providers mentioned
    providers: set[str] = set()
    for cat_data in comparison.values():
        for key in cat_data:
            if key.endswith("_mean_s"):
                providers.add(key.removesuffix("_mean_s"))
    providers_sorted = sorted(providers)

    header = "| Category |" + " | ".join(f" {p.capitalize()} (mean) " for p in providers_sorted) + " |"
    sep = "|----------|" + " | ".join("----:" for _ in providers_sorted) + " |"
    lines.append(header)
    lines.append(sep)

    for cat, cat_data in sorted(comparison.items()):
        cols = []
        for p in providers_sorted:
            val = cat_data.get(f"{p}_mean_s")
            cols.append(_fmt(val) if val is not None else "-")
        slowdown = cat_data.get("slowdown_factor", {})
        # Add slowdown annotation to last column if available
        if slowdown:
            first_pair = next(iter(slowdown.items()), None)
            if first_pair:
                factor = first_pair[1]
                cols[-1] += f" ({factor:.1f}x)"
        lines.append(f"| {cat} | " + " | ".join(cols) + " |")

    lines.append("")
    return lines


def generate_comment(json_paths: list[str]) -> str:
    # Merge all JSON reports
    all_summary: dict = {}
    all_comparison: dict = {}
    providers_tested: list[str] = []

    for path in json_paths:
        p = Path(path)
        if not p.exists():
            continue
        with open(p) as f:
            data = json.load(f)
        for provider in data.get("providers_tested", []):
            if provider not in providers_tested:
                providers_tested.append(provider)
        all_summary.update(data.get("summary", {}))
        # Merge comparison (later files override)
        all_comparison.update(data.get("cross_provider_comparison", {}))

    if not all_summary:
        return ""

    lines: list[str] = []
    lines.append("## Sandbox Integration Test Metrics")
    lines.append("")

    for provider in providers_tested:
        if provider in all_summary:
            lines.extend(_provider_table(provider, all_summary[provider]))

    if len(providers_tested) > 1 and all_comparison:
        lines.extend(_comparison_table(all_comparison))

    lines.append("---")
    lines.append(
        "<sub>Generated by sandbox-integration CI</sub>"
    )

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <metrics.json> [metrics2.json ...]", file=sys.stderr)
        sys.exit(1)

    comment = generate_comment(sys.argv[1:])
    if comment:
        print(comment)
    else:
        print("No metrics data found.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
